using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SourceGenerator
{
    public class CodeChunkCodeGenerator
    {
        public CodeChunkCodeGenerator(GeneratorExecutionContext context) 
        {
            _context = context;
        }

        private readonly GeneratorExecutionContext _context;

        public void Run(TargetCodeChunksCompilationUnit targetCompilationUnit)
        {
#if DEBUG
            //FileLogger.WriteLn($"targetCompilationUnit = {targetCompilationUnit}");
#endif

            var requredNamespaces = new List<string>()
            {
                "using TestSandBox.SerializedObjects;"
            };

            if (targetCompilationUnit.Usings?.Any() ?? false)
            {
                requredNamespaces.AddRange(targetCompilationUnit.Usings);
            }

            var sourceCodeBuilder = new StringBuilder();
            sourceCodeBuilder.AppendLine("// <autogenerated />");
            foreach (var item in requredNamespaces.Distinct())
            {
                sourceCodeBuilder.AppendLine(item);
            }

            foreach (var targetCodeChunkItem in targetCompilationUnit.CodeChunkItems)
            {
                ProcessTargetCodeChunkItem(targetCodeChunkItem, sourceCodeBuilder);
            }

#if DEBUG
            //FileLogger.WriteLn($"sourceCodeBuilder = {sourceCodeBuilder}");
#endif

            var firstCodeChunkItem = targetCompilationUnit.CodeChunkItems.First();

#if DEBUG
            //FileLogger.WriteLn($"firstCodeChunkItem = {firstCodeChunkItem}");
#endif

            var fileName = $"{GetClassName(firstCodeChunkItem)}.g.cs";

            SaveFile(sourceCodeBuilder.ToString(), fileName);
        }

        private void ProcessTargetCodeChunkItem(CodeChunkItem targetCodeChunkItem, StringBuilder sourceCodeBuilder)
        {
#if DEBUG
            //FileLogger.WriteLn($"targetCodeChunkItem = {targetCodeChunkItem}");
            //GeneratorsHelper.ShowSyntaxNode(0, targetClassItem.SyntaxNode);
#endif

            var identationStep = 4;
            var baseIdentation = 0;
            var classDeclIdentation = baseIdentation + identationStep;
            var classContentDeclIdentation = classDeclIdentation + identationStep;
            var classContentIdentation = classContentDeclIdentation + identationStep;

            sourceCodeBuilder.AppendLine();
            sourceCodeBuilder.AppendLine($"namespace {targetCodeChunkItem.Namespace}.ActionFactories");
            sourceCodeBuilder.AppendLine("{");
            sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classDeclIdentation)}[SocSerializableAction(Id = \"{targetCodeChunkItem.Identifier}\")]");
            sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classDeclIdentation)}public class {GetClassName(targetCodeChunkItem)} : ISocSerializableActionFactory");
            sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classDeclIdentation)}{{");
            sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentDeclIdentation)}public string Id => \"{targetCodeChunkItem.Identifier}\";");
            
            var actionFieldsDict = new Dictionary<int, string>();

            var useIndexInActionFieldName = targetCodeChunkItem.Lambdas.Count > 1;

#if DEBUG
            //FileLogger.WriteLn($"useIndexInActionFieldName = {useIndexInActionFieldName}");
#endif

            var n = 0;

            foreach (var lambda in targetCodeChunkItem.Lambdas)
            {
#if DEBUG
                //GeneratorsHelper.ShowSyntaxNode(0, lambda);
#endif

                var actionTypeName = GetActionTypeName(lambda);

#if DEBUG
                //FileLogger.WriteLn($"actionTypeName = '{actionTypeName}'");
#endif

                var actionName = GetActionFieldName(useIndexInActionFieldName, n);

#if DEBUG
                //FileLogger.WriteLn($"actionName = '{actionName}'");
#endif

                sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentDeclIdentation)}private {actionTypeName} {actionName} = {lambda.GetText()};");

                n++;

                actionFieldsDict[n] = actionTypeName;
            }

            if(useIndexInActionFieldName)
            {
                sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentDeclIdentation)}public object GetAction(int index)");
                sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentDeclIdentation)}{{");
                sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentIdentation)}switch(index)");
                sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentIdentation)}{{");
                foreach(var actionFieldItem in actionFieldsDict)
                {
                    sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentIdentation)}case {actionFieldItem.Key}: return {actionFieldItem.Value};");
                }
                sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentIdentation)}default: return null;");
                sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentIdentation)}}}");
                sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentDeclIdentation)}}}");
            }
            else
            {
                sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classContentDeclIdentation)}public object GetAction(int index) => _action;");
            }

            sourceCodeBuilder.AppendLine($"{GeneratorsHelper.Spaces(classDeclIdentation)}}}");
            sourceCodeBuilder.AppendLine("}");
        }

        private string GetClassName(CodeChunkItem targetCodeChunkItem)
        {
            return $"SocSerializableActionFactory{targetCodeChunkItem.Identifier.Replace("-", string.Empty)}";
        }

        private string GetActionFieldName(bool useIndexInActionFieldName, int n)
        {
#if DEBUG
            //FileLogger.WriteLn($"useIndexInActionFieldName = {useIndexInActionFieldName}");
            //FileLogger.WriteLn($"n = {n}");
#endif

            if(useIndexInActionFieldName)
            {
                return $"_action{n}";
            }

            return "_action";
        }

        private string GetActionTypeName(ParenthesizedLambdaExpressionSyntax lambda)
        {
#if DEBUG
            //GeneratorsHelper.ShowSyntaxNode(0, lambda);
#endif

            var parameterList = lambda.ParameterList;

            var parameterListChildNodes = parameterList.ChildNodes();

#if DEBUG
            //FileLogger.WriteLn($"parameterListChildNodes.Count() = {parameterListChildNodes.Count()}");
#endif

            if(parameterListChildNodes.Count() == 0)
            {
                return "Action";
            }

#if DEBUG
            //FileLogger.WriteLn($"lambda.ChildNodes().Count() = {lambda.ChildNodes().Count()}");
#endif

            var actionTypeName = string.Empty;
            var needToAddFuncResultType = false;
            var funcResultType = string.Empty;

            if (lambda.ChildNodes().Count() == 2)
            {
                actionTypeName = "Action";
            }
            else
            {
                needToAddFuncResultType = true;
                actionTypeName = "Func";

                var funcTypeNode = lambda.ChildNodes().ElementAt(0);

#if DEBUG
                //GeneratorsHelper.ShowSyntaxNode(0, funcTypeNode);
#endif

                funcResultType = GeneratorsHelper.ToString(funcTypeNode.GetText());
            }

            var genericTypeList = new List<string>();

            foreach(var parameter in parameterList.Parameters)
            {
#if DEBUG
                //GeneratorsHelper.ShowSyntaxNode(0, parameter);
#endif

                var identifierName = parameter.ChildNodes().FirstOrDefault(p => p.IsKind(SyntaxKind.IdentifierName));

                if(identifierName == null)
                {
                    var genericName = parameter.ChildNodes().FirstOrDefault(p => p.IsKind(SyntaxKind.GenericName));

                    if(genericName == null)
                    {
                        var predefinedType = parameter.ChildNodes().FirstOrDefault(p => p.IsKind(SyntaxKind.PredefinedType));

                        if(predefinedType == null)
                        {
                            genericTypeList.Add(string.Empty);
                        }
                        else
                        {
                            genericTypeList.Add(GeneratorsHelper.ToString(predefinedType.GetText()));
                        }
                    }
                    else
                    {
                        genericTypeList.Add(GeneratorsHelper.ToString(genericName.GetText()));
                    }
                }
                else
                {
                    genericTypeList.Add(GeneratorsHelper.ToString(identifierName.GetText()));
                }
            }

#if DEBUG
            //FileLogger.WriteLn($"needToAddFuncResultType = {needToAddFuncResultType}");
            //FileLogger.WriteLn($"funcResultType = '{funcResultType}'");
#endif

            if (needToAddFuncResultType)
            {
                genericTypeList.Add(funcResultType);
            }

            return $"{actionTypeName}<{string.Join(",", genericTypeList)}>";
        }

        private void SaveFile(string source, string fileName)
        {
            _context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
        }
    }
}
